name: Build and Checks

on:
  workflow_dispatch:
  push:
    branches: '*'
  pull_request:
    branches: '*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/base-builder:ubuntu.0.1.7.b18
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get update
        apt-get -y install libpcap-dev libxml2-dev libunwind-dev libfuse3-dev fuse3 liblz4-dev
        ( git clone --depth 1 https://github.com/CESNET/nemea-framework /tmp/nemea-framework; cd /tmp/nemea-framework; ./bootstrap.sh &&./configure --bindir=/usr/bin/nemea/ -q &&make -j10 && sudo make install; sudo ldconfig)
        ( git clone --depth 1 https://github.com/CESNET/nemea-modules /tmp/nemea-modules; cd /tmp/nemea-modules; ./bootstrap.sh &&./configure --bindir=/usr/bin/nemea/ -q &&make -j10 && sudo make install; )
        ( git clone -b release --depth 1 https://github.com/CESNET/telemetry /tmp/telemetry; cd /tmp/telemetry; mkdir build && cd build; cmake -DCMAKE_INSTALL_PREFIX=/usr .. &&make -j10 && sudo make install; )
    - name: autoreconf
      run: autoreconf -i
    - name: configure
      run: ./configure --with-raw --with-pcap --with-nemea --with-gtest
    - name: make
      run: make
    - name: Build Debian packages
      run: make deb
